config/routes.rb
Rails.application.routes.draw do
	root "welcome#index"  
	
	resources :pessoas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
	def index
		@pessoas = Pessoa.all
	end

	def new
		@pessoa = Pessoa.new
	end

	def create
		@pessoa = Pessoa.create(params_pessoa)

		# Caso salve
		if @pessoa.save
			redirect_to pessoas_path
		else
			redirect_to root_path
		end
	end

	def edit
		@pessoa = Pessoa.find_by id: params[:id]
	end

	def update
		@pessoa = Pessoa.find_by id: params[:id]
		@pessoa.update_attributes(params_pessoa)

		if @pessoa.save
			redirect_to pessoas_path
		else
			redirect_to root_path
		end
	end

	def destroy
		@pessoa = Pessoa.find_by id: params[:id]

		# Verifica se consegue apagar
		if @pessoa.delete
			redirect_to pessoas_path
		else
			redirect_to root_path
		end
	end

	private
	def params_pessoa
		params.require(:pessoa).permit(:nome, :idade)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@nome = Pessoa.last.nome
		@eu = Pessoa.first
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDeTeste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if request.original_url != (request.base_url + root_path) %>
      <div class='nav'>
        <%= link_to 'Inicio', root_path %>

        <%= link_to 'Adicionar Pessoa', new_pessoa_path %>

        <%= link_to 'Todas as Pessoas', pessoas_path %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pessoas/edit.html.erb
<h1>Editar pessoa</h1>

<%= form_for @pessoa do |pessoa| %>
	<p>
		Nome:
		<%= pessoa.text_field :nome %>
	</p>

	<p>
		Idade:
		<%= pessoa.text_field :idade %>
	</p>

	<%= pessoa.submit %>
<% end %>

app/views/pessoas/index.html.erb
<h1>Veja todas as pessoas aqui</h1>

<br><br>

<% @pessoas.each do |pessoa| %>
	<p>
		<%= pessoa.idade %> - 
		<%= pessoa.nome %>
		<%= link_to 'Apagar', pessoa_path(pessoa.id), method: :delete %>		
		<%= link_to 'Editar', edit_pessoa_path(pessoa.id) %>
	</p>
<% end %>

app/views/pessoas/new.html.erb
<%= form_for @pessoa do |pessoa| %>
	<p>
		Nome: 
		<%= pessoa.text_field :nome %>		
	</p>

	<p>
		Idade:
		<%= pessoa.text_field :idade %>
	</p>
	<%= pessoa.submit %>
<% end%>

app/views/welcome/index.html.erb
<h1>Oque você deseja Fazer?</h1>

<%= link_to 'Adicionar Pessoa', new_pessoa_path %>

<%= link_to 'Ver Todas as Pessoas', pessoas_path %>